version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Replace with the Docker image you use for your project
    steps:
      - checkout  # Check out the code from the repository

      # Example: Create the file in the Downloads directory
      - run:
          name: Create a file in Downloads directory
          command: |
            mkdir -p ~/Downloads
            pip install yt-dlp 
            yt-dlp ~/Downloads/ "https://vd437.okcdn.ru/expires/1733934554342/srcIp/216.10.217.170/srcAg/CHROME_ANDROID/ms/45.136.21.36/type/2/sig/Eo71wd0BsV4/ct/8/urls/185.226.55.24/clientType/1/zs/43/id/742986811931/video/"        
      # Store the file in CircleCI artifacts
      - store_artifacts:
          path: ~/Downloads
          destination: artifact

workflows:
  version: 2
  build_and_store:
    jobs:
      - build
