version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Replace with the Docker image you use for your project
    steps:
      - checkout  # Check out the code from the repository

      # Example: Create the file in the Downloads directory
      - run:
          name: Create a file in Downloads directory
          command: |
            mkdir -p ~/Downloads
            echo "This is an example file" > ~/Downloads/example.txt

      # Store the file in CircleCI artifacts
      - store_artifacts:
          path: ~/Downloads/example.txt
          destination: example_files

workflows:
  version: 2
  build_and_store:
    jobs:
      - build
