version: '2.1'
orbs:
  python: circleci/python@3.0.0
jobs:
  publish:
    executor: python/default
    steps:
      - checkout
      - python/dist
      - run: pip install aria2 
  parallel_downloads:
    executor: aria2-executor
    parallelism: 4  # This will run 4 containers in parallel for the same job
    steps:
      - run:
          name: Download files with Aria2c in parallel
          command: |
            echo "Starting download tasks..."
            aria2c --seed-time=0 "magnet:?xt=urn:btih:76D2015AC0445F1DCA0E8847E08D9093BB03CE50&tr=udp%3A%2F%2Ftracker.breizh.pm%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fpow7.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fwww.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Ftracker.bitsearch.to%3A1337%2Fannounce&dn=%5BBitsearch.to%5D+Black+Widow+(2021)+%5B1080p%5D+%5BWEBRip%5D+%5B5.1%5D+%5BYTS.MX%5D"
workflows:
  main:
    jobs:
      - python/test:
          args: '--dev'
          pkg-manager: pipenv
          test-tool: pytest
      - publish
