version: '2.1'
orbs:
  python: circleci/python@3.0.0
  aria2: circleci/aria2@1.0.0  # Add Aria2 orb for better integration
executors:
  python-default:
    docker:
      - image: circleci/python:3.8
        environment:
          PIP_CACHE_DIR: /tmp/pip_cache
  aria2-executor:
    docker:
      - image: circleci/python:3.8
        environment:
          PIP_CACHE_DIR: /tmp/pip_cache
workflows:
  version: 2
  main:
    jobs:
      - python/test:
          args: '--dev'
          pkg-manager: pipenv
          test-tool: pytest
      - publish:
          requires:
            - python/test
      - parallel_downloads:
          requires:
            - publish

jobs:
  publish:
    executor: python-default
    steps:
      - checkout
      - python/install-packages:
          packages: 
            - aria2
      - run:
          name: Run Python tests
          command: pipenv install && pipenv run pytest
          
  parallel_downloads:
    executor: aria2-executor
    parallelism: 4
    steps:
      - run:
          name: Download files with Aria2c in parallel
          command: |
            echo "Starting download tasks..."
            aria2c --seed-time=0 -d ~/Downloads "magnet:?xt=urn:btih:8DA0E1A2026D061E2BBABB1A663D4711C848F819&dn=example"
      - store_artifacts:
          path: ~/Downloads
          destination: example_files
