version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Replace with the Docker image you use for your project
    steps:
      - checkout  # Check out the code from the repository

      # Example: Create the file in the Downloads directory
      - run:
          name: Create a file in Downloads directory
          command: |
            mkdir -p ~/Downloads
            pip install yt-dlp
            yt-dlp -f "bestvideo[height<=720]+bestaudio/best[height<=720]" -o "/home/circleci/downloads/%(title)s.%(ext)s" "https://m.youtube.com/playlist?list=PL75WpgEj_KA2H_6ctlw4nDljtTmg88a9v"
      # Store the file in CircleCI artifacts
      - store_artifacts:
          path: ~/Downloads
          destination: artifact

workflows:
  version: 2
  build_and_store:
    jobs:
      - build
