name: Torrent Download & Upload to Pixeldrain

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  torrent-upload:
    runs-on: ubuntu-latest
    env:
      PIXELDRAIN_API_KEY: '8ec6f000-e8d1-403d-820b-4324a6a68869'  # Replace with your actual API key
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install -g webtorrent-cli
        
      - name: Download torrent content with webtorrent-cli
        run: |
          webtorrent download "magnet:?xt=urn:btih:c826e50fcfd41b1fe0be4d89d97eb33772eb240d&dn=Big%20City%20Greens%20S04E50%20After%20Dark%20720p%20HULU%20WEB-DL%20DDP5%201%20H%20264-NTb%5BEZTVx.to%5D.mkv%5Beztv%5D&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce" "magnet:?xt=urn:btih:07f048a944173dbc1054136e0194a6f34791c57c&dn=Big%20City%20Greens%20S04E49%20Flexed%20720p%20HULU%20WEB-DL%20DDP5%201%20H%20264-NTb%5BEZTVx.to%5D.mkv%5Beztv%5D&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce" "magnet:?xt=urn:btih:27d8f73516d68e7b3fe06eb8fee1b0f60b194de3&dn=Kiff%20S02E30%20A%20Troll%20Through%20the%20Woods%20720p%20HULU%20WEB-DL%20DDP5%201%20H%20264-NTb%5BEZTVx.to%5D.mkv%5Beztv%5D&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce" "magnet:?xt=urn:btih:2f12306982728e133ce4d544f3c67695f3c52605&dn=Kiff%20S02E31%20Big%20Coat%201080p%20HULU%20WEB-DL%20DDP5%201%20H%20264-NTb%5BEZTVx.to%5D.mkv%5Beztv%5D&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce" "magnet:?xt=urn:btih:032aab6f7335ebdb0ee25f3512bbbe3f4029d36d&dn=Wylde%20Pak%20S01E10%20The%20Meatball%20of%20Canyon%20Valley%201080p%20AMZN%20WEB-DL%20DDP2%200%20H%20264-NTb%5BEZTVx.to%5D.mkv%5Beztv%5D&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce" "magnet:?xt=urn:btih:a06fa0945a5baf468c9c5296dbedc2c91dbd1a18&dn=Wylde%20Pak%20S01E11%20Sticky%20Fingers%201080p%20AMZN%20WEB-DL%20DDP2%200%20H%20264-NTb%5BEZTVx.to%5D.mkv%5Beztv%5D&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce" --out ./downloaded_files

      - name: Upload all downloaded files (recursive)
        run: |
          find ./downloaded_files -type f -print0 | while IFS= read -r -d '' file; do
                curl -g -X POST "https://upload.gofile.io/uploadfile" \
                     -H "Authorization: Bearer NkEP9nPmjC5bYQB7ZabZKnsUEBi7ww85" \
                     -F "file=@\"$file\"" \
                     -F "folderId=569169f0-479c-4720-857a-2aa341d5eca9"
              done
