name: YouTube Video Download

on:
  push:
    branches:
      - main  # Change this to your default branch as necessary

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install yt-dlp Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y yt-dlp

      - name: Download YouTube Video
        run: |
          # Create a directory to store the downloads
          mkdir -p downloads
          
          # Download the YouTube video using yt-dlp
          yt-dlp -o "downloads/%(title)s.%(ext)s" "https://m.youtube.com/watch?v=S82TtBYo0Kg"

      - name: Upload Video as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: youtube-video
          path: downloads/
